version: "2.1"
services:
  maven-gm:
    # 1.) Do not use the alpine image as it fails frontend-maven-plugin:install-node-and-yarn
    #     https://github.com/eirslett/frontend-maven-plugin/issues/743
    # 2.) Avoid 3.5.4 or higher for now, surefire fails due to a broken openjdk package
    #     https://github.com/carlossg/docker-maven/issues/90
    image: 'imgsrv-maven-with-graphicsmagick:3.5.0-jdk-8'
    build:
      context: .
      dockerfile: 'Dockerfile'
    working_dir: '${WORKING_DIR:-/usr/src/app}'
    container_name: imageserver-container
    volumes:
      - '.:/usr/src/app:delegated'
      # remap the local gm bash script in docker to the actual gm binary
      - './gm-docker:/usr/src/app/gm'
      - './docker-build-files/wait-for-it.sh:/root/wait-for-it.sh'
      - './docker-build-files/wait-for-datasource.jar:/root/wait-for-datasource.jar'
      # TODO: should we map the dev-configs volume or just include it in our repo?
      - './docker-build-files/dev-configs:/root/dev-configs'
      # Reuse the maven repository from the host, we could omit it, but it would fetch at each build
      - '${HOME}/.m2:/root/.m2:delegated'
      # Reuse embedded mongo db downloads
      - '${HOME}/.embedmongo:/root/.embedmongo:delegated'
    # WINDOWS USERS using cmd.exe:
    #- '${USERPROFILE}/.m2:/root/.m2'
    stdin_open: true
    environment:
      # Specify the timezone - used by date tests
      TZ: "Europe/Brussels"
      # Specify a language - used by LocaleContextHolder
      LANG: "en_US.UTF-8"
      # Required by embedded mongo db - across-autoconfigure/test-projects
      LC_ALL: "C"
    command: bash