version: '2.1'
services:
  localstack:
    image: 'localstack/localstack:0.9.3'
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8099}:${PORT_WEB_UI-8099}"
    environment:
#      - SERVICES=${SERVICES- }
      - SERVICES=s3
      - DEBUG=${DEBUG- }
      #- DATA_DIR=${DATA_DIR- }
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI-8099}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - ./local-data/storage/localstack:/tmp/localstack/data