across:
  development:
    active: true

server:
  port: 8078

spring:
  datasource:
    url: "jdbc:h2:./local-data/db/imageserver-test-embedded-db"
    username: sa

imageServerCore:
  store:
    folder: local-data/images
  transformers:
    imageMagick:
      path: ./