spring:
  datasource:
    url: jdbc:h2:../local-data/remote-imageserver/application-db

webCmsModule:
  images:
    imageServer:
      # Actual ImageServer credentials should be added to the local application config: ${user.home}/dev-configs/wcm-test-application.yml
      enabled: true
