spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:../local-data/db/file-manager-module
    username: sa

across:
  development:
    active: true
adminWebModule:
  title: Admin FMM
  login:
    rememberMe:
      key: filemanagermodule
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
security:
  basic:
    enabled: false

fileManagerModule:
  localRepositoriesRoot: "../local-data/fmm-test-files"

acrossHibernate:
  hibernate-properties:
    hibernate.hbm2ddl.auto: update
