spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:../local-data/db/file-manager-module
    username: sa

across:
  development:
    active: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
security:
  basic:
    enabled: false

fileManagerModule:
  localRepositoriesRoot: "${user.home}/fmm-test-files"
